apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-cool-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: my-cool-service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-cool-service
            port:
              number: 8000
