apiVersion: v1
kind: Service
metadata:
  name: my-cool-service
spec:
  selector:
    app: my-cool-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31234
  type: NodePort
